# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_semaphore
  end

  desc "Push a new release build to the App Store"
  lane :release do
    match(type: "appstore")
    increment_build_number(
      xcodeproj: "Oak.xcodeproj"
    )
    build_app(scheme: "Oak")
    upload_to_app_store
  end

  desc "Build Project"
  lane :build do
    build_app(
      skip_codesigning: true,
      skip_archive: true,
      scheme: "Oak",
    )
  end


  desc "Run Unit tests"
  lane :unit do
    run_tests(
      scheme: "OakTests",
      test_without_building: true,
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
    )
  end
end
