# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_semaphore
  end

  desc "Run Unit tests"
  lane :test do
    run_tests(
      scheme: "OakTests",
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
      result_bundle: true,
      device: "iPhone 12 Pro Max",
      output_types: "junit",
    )
  end

  desc "Test, build & upload app to appstore"
  lane :publish do
    test
    match(type: "appstore")
    increment_build_number
    build_app(scheme: "Oak")
    upload_to_app_store(
      force: true,
      skip_screenshots: true,
    )
  end
end
